title:              Development as Freedom
email:              duongthuvn@protonmail.com
description:        Economics x Data
author:             Me
# baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://non-ceterisparibus.github.io"

# Social Profiles
twitter_username: duongthuvn
github_username: non-ceterisparibus
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
